Snap stable build config for 4.3.0

diff --git a/.snapcraft.yaml b/.snapcraft.yaml
--- a/.snapcraft.yaml
+++ b/.snapcraft.yaml
@@ -1,11 +1,17 @@
 name: warzone2100 # no spaces, all lower-case
 # summary, description, and icon are parsed from the appdata/metainfo file
-adopt-info: warzone2100
+adopt-info: warzone2100 # specify the *part* name
 confinement: strict
 grade: stable
-base: core18
+base: core20
 # Enable LZO compression for the snap
 compression: lzo
+# Limit architectures to those supported by the gnome extension (and future core20)
+# NOTE: Specify these as separate build-on lines to ensure separate architecture builds that each support a single architecture
+architectures:
+  - build-on: amd64
+  - build-on: arm64
+  - build-on: armhf
 layout:
   /usr/share/vulkan:
     symlink: $SNAP/usr/share/vulkan
@@ -13,6 +19,14 @@ layout:
     symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_intel.so
   /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so:
     symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_radeon.so
+#  # Try the following once base is updated to core22
+#  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_broadcom.so:
+#    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_broadcom.so
+#  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_freedreno.so:
+#    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_freedreno.so
+#  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so:
+#    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvulkan_lvp.so
+
 plugs:
   wz2100-sequences:
     interface: content
@@ -21,10 +35,10 @@ plugs:
     default-provider: warzone2100-videos
 apps:
   warzone2100:
+    extensions: [gnome-3-38]
     command: usr/bin/warzone2100
-    command-chain: [bin/desktop-launch]
-    common-id: warzone2100 # should match the appdata/metainfo file's <id> field
-    desktop: usr/share/applications/warzone2100.desktop
+    common-id: net.wz2100.warzone2100 # should match the appdata/metainfo file's <id> field
+    desktop: usr/share/applications/net.wz2100.warzone2100.desktop
     plugs:
       - audio-playback
       - desktop
@@ -36,45 +50,12 @@ apps:
       - unity7
       - wayland
       - x11
-  download-videos:
-    command: bin/download-videos
-    plugs: [network]
 parts:
-  scripts:
-    plugin: dump
-    source: pkg/snap
-    organize:
-      download-videos: bin/download-videos
-    stage-packages:
-      - curl
-  desktop-qt5:
-    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
-    source-subdir: qt
-    plugin: make
-    make-parameters: ["FLAVOR=qt5"]
-    build-packages:
-      - qtbase5-dev
-      - dpkg-dev
-    stage-packages:
-      - libxkbcommon0
-      - ttf-ubuntu-font-family
-      - dmz-cursor-theme
-      - light-themes
-      - adwaita-icon-theme
-      - gnome-themes-standard
-      - shared-mime-info
-      - libqt5gui5
-      - libgdk-pixbuf2.0-0
-      - libqt5svg5 # for loading icon themes which are svg
-      - qtwayland5
-      - try: [appmenu-qt5] # not available on core18
-      - locales-all
-      - libgtk2.0-0
   sdl:
-    source: https://www.libsdl.org/release/SDL2-2.0.14.tar.gz
-    source-checksum: sha512/ebc482585bd565bf3003fbcedd91058b2183e333b9ea566d2f386da0298ff970645d9d25c1aa4459c7c96e9ea839fd1c5f2da0242a56892865b2e456cdd027ee
+    source: https://www.libsdl.org/release/SDL2-2.0.20.tar.gz
+    source-checksum: sha512/4889949eaa674948bdb0a01bb2a842a0943b15b08ff27ec0079b0fd4f79d071ffb32488a5a51c12ad7c74ed5fe73b608cdf6336a44c95dae8a0fb3f47d0f01de
     plugin: autotools
-    configflags:
+    autotools-configure-parameters:
       - --prefix=/usr
       - --disable-alsa
       - --disable-arts
@@ -102,6 +83,7 @@ parts:
       - libwayland-dev
       - libx11-dev
       - libxcursor-dev
+      - libxfixes-dev
       - libxext-dev
       - libxi-dev
       - libxinerama-dev
@@ -110,11 +92,13 @@ parts:
       - libxrender-dev
       - libxss-dev
       - libxxf86vm-dev
+      - libgbm-dev
     stage-packages:
       - libdbus-1-3
       - libudev1
       - fcitx-libs
       - libdrm2
+      - libgbm1
       - libegl1-mesa
       - libgl1
       - libgles2
@@ -125,11 +109,13 @@ parts:
       - libts0
       - libsndfile1
       - libwayland-client0
+      - libwayland-cursor0
       - libwayland-egl1-mesa
       - libvulkan1
       - libx11-6
       - libxcursor1
       - libxext6
+      - libxfixes3
       - libxi6
       - libxinerama1
       - libxkbcommon0
@@ -138,13 +124,13 @@ parts:
       - libxss1
       - libxxf86vm1
   warzone2100:
-    after: [desktop-qt5, sdl]
+    after: [sdl]
     plugin: cmake
     source: https://github.com/Warzone2100/warzone2100.git
     parse-info:
       # Parse this appdata/metainfo file for summary, description,
       # and icon. Use the installed path relative to the Snap's root
-      - usr/share/metainfo/warzone2100.appdata.xml
+      - usr/share/metainfo/net.wz2100.warzone2100.appdata.xml
     override-pull: |
       # Obtain the desired tag from the .stable_tag file
       echo "SNAPCRAFT_PROJECT_DIR=$SNAPCRAFT_PROJECT_DIR"
@@ -178,6 +164,7 @@ parts:
       . "${SNAPCRAFT_PART_SRC}/.ci/snap/install_vulkan_sdk.sh"
 
       if [ -f ".snapenv" ]; then set -a; source .snapenv; set +a; fi
+      set +u
       if [ -z "$WZ_DISTRIBUTOR" ]; then export WZ_DISTRIBUTOR="UNKNOWN"; fi
       cmake -S "$SNAPCRAFT_PART_SRC" -B. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DWZ_ENABLE_WARNINGS:BOOL=ON -DWZ_DISTRIBUTOR:STRING="${WZ_DISTRIBUTOR}" -DWZ_OUTPUT_NAME_SUFFIX="${WZ_OUTPUT_NAME_SUFFIX}" -DWZ_NAME_SUFFIX="${WZ_NAME_SUFFIX}" -G"Ninja"
       cmake --build . -- -j$SNAPCRAFT_PARALLEL_BUILD_COUNT
@@ -185,20 +172,21 @@ parts:
 
       # Include the icon's path in the desktop file, not just the name.
       # This needs to happen post-build or the build versioning will show as "modified locally"
-      sed -i -E 's|Icon=(.*)|Icon=/usr/share/icons/\1.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/warzone2100.desktop
+      sed -i -E 's|Icon=(.*)|Icon=/usr/share/icons/\1.png|' $SNAPCRAFT_PART_INSTALL/usr/share/applications/net.wz2100.warzone2100.desktop
     build-packages:
       - asciidoctor
       - g++
       - gettext
       - libfontconfig1-dev
-      - libfreetype6-dev
+      - libfreetype-dev
       - libfribidi-dev
-      - libglc-dev
       - libharfbuzz-dev
       - libopenal-dev
       - libphysfs-dev
       - libpng-dev
       - libtheora-dev
+      - libogg-dev
+      - libopus-dev
       - libvorbis-dev
       - libcurl4-gnutls-dev
       - libgnutls28-dev
@@ -212,10 +200,10 @@ parts:
       - libfontconfig1
       - libfreetype6
       - libfribidi0
-      - libglc0
       - libharfbuzz0b
       - libogg0
       - libopenal1
+      - libopus0
       - libphysfs1
       - libpng16-16
       - libtheora0
@@ -231,3 +219,29 @@ parts:
       - unzip
       - zip
     source-type: git
+  # This part removes all the files in this snap which already exist in
+  # connected content and base snaps. Since these files will be available
+  # at runtime from the content and base snaps, they do not need to be
+  # included in this snap itself.
+  #
+  # More info: https://forum.snapcraft.io/t/reducing-the-size-of-desktop-snaps/17280#heading--cleanup-part
+  #
+  cleanup:
+    after: # Make this part run last; list all your other parts here
+      - sdl
+      - warzone2100
+    plugin: nil
+    build-snaps: # List all content-snaps and base snaps you're using here
+      - core20
+      - gtk-common-themes
+      - gnome-3-38-2004
+    override-prime: |
+      set -eux
+      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do  # List all content-snaps and base snaps you're using here
+          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
+      done
+      # The following is required while using core18 + gnome-3-34
+      # See: https://forum.snapcraft.io/t/undefined-symbol-hb-buffer-set-invisible-glyph-with-gnome-3-34/24287
+      rm -f $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libharfbuzz.so.0*
+      rm -f $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgio-2.0.so.0*
+      rm -f $SNAPCRAFT_PRIME/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libglib-2.0.so.0*
